version: "3.9"
services:
  db:
    image: library/postgres:13-alpine
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - app_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bb_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ENV: development
  app:
    depends_on:
      - db
    build:
      args:
        ENV: development
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bb_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  app_postgres: