version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    command: [ "java" ,"-jar", "app.jar" ]
    entrypoint: /usr/bin/entrypoint.sh
    ports:
      - "${PORT}:8100"