# TODO - Store db and app ports, database credentials in environment variables for dev and prod environments
version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "java" ,"-jar", "app.jar" ]
    entrypoint: /usr/bin/entrypoint.sh
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8100:8100"