version: "3.9"
services:
  app:
    environment:
      ENV: production
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    build:
      args:
          ENV: production
          SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
          SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
          SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
