const PORT: number = 8100;
export const BASE_URL: string = `http://localhost:${PORT}/`;

export const RELATIVE_USER_ENDPOINT: string = "user/";
export const RELATIVE_USER_LOGIN_ENDPOINT: string = RELATIVE_USER_ENDPOINT + "login";
export const RELATIVE_USER_REGISTER_ENDPOINT: string = RELATIVE_USER_ENDPOINT + "register";

export const FULL_USER_ENDPOINT: string = BASE_URL + RELATIVE_USER_ENDPOINT;
export const FULL_USER_LOGIN_ENDPOINT: string = FULL_USER_ENDPOINT + RELATIVE_USER_LOGIN_ENDPOINT;
export const FULL_USER_REGISTER_ENDPOINT: string = FULL_USER_ENDPOINT + RELATIVE_USER_REGISTER_ENDPOINT;