CREATE TABLE USER
(
    USERNAME VARCHAR(30)  NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE LEAGUE
(
    LEAGUE_ID   INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    USERNAME    VARCHAR(30) NOT NULL,
    NAME        VARCHAR(30) NOT NULL,
    START_DATE  DATE        NOT NULL,
    LAST_PLAYED DATE        NOT NULL,
    PRIMARY KEY (LEAGUE_ID),
    FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME)
);

CREATE TABLE LEAGUE_SEASON
(
    LEAGUE_ID INT      NOT NULL,
    SEASON    SMALLINT NOT NULL,
    GAME_DATE DATE     NOT NULL,
    PRIMARY KEY (LEAGUE_ID, SEASON),
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE (LEAGUE_ID)
);

CREATE TABLE TEAM_ICON
(
    ICON_ID INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ICON    VARCHAR(25) NOT NULL,
    PRIMARY KEY (ICON_ID)
);

CREATE TABLE TEAM_NAME
(
    TEAM_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (TEAM_NAME)
);

CREATE TABLE TEAM_STATE
(
    TEAM_STATE VARCHAR(50) NOT NULL,
    PRIMARY KEY (TEAM_STATE)
);

CREATE TABLE TEAM
(
    TEAM_ID      INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TEAM_STATE   VARCHAR(48) NOT NULL,
    TEAM_NAME    VARCHAR(50) NOT NULL,
    RELOCATIONS  INT DEFAULT 0,
    RENAMES      INT DEFAULT 0,
    IS_USER_TEAM BOOLEAN     NOT NULL,
    DATE_FOUNDED DATE        NOT NULL,
    ICON_ID      INT         NOT NULL,
    LEAGUE_ID    INT         NOT NULL,
    PRIMARY KEY (TEAM_ID),
    FOREIGN KEY (TEAM_STATE) REFERENCES TEAM_STATE (TEAM_STATE),
    FOREIGN KEY (TEAM_NAME) REFERENCES TEAM_NAME (TEAM_NAME),
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE (LEAGUE_ID),
    FOREIGN KEY (ICON_ID) REFERENCES TEAM_ICON (ICON_ID)
);

CREATE TABLE ARCHETYPE
(
    ARCHETYPE_ID SMALLINT     NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME         VARCHAR(25)  NOT NULL UNIQUE,
    DESCRIPTION  VARCHAR(255) NOT NULL,
    PRIMARY KEY (ARCHETYPE_ID)
);

CREATE TABLE COLLEGE
(
    COLLEGE VARCHAR(25) NOT NULL,
    PRIMARY KEY (COLLEGE)
);

CREATE TABLE FIRST_NAME
(
    FIRST_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (FIRST_NAME)
);

CREATE TABLE LAST_NAME
(
    LAST_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (LAST_NAME)
);

CREATE TABLE PLAYER
(
    PLAYER_ID          INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TEAM_ID            INT         NOT NULL,
    FIRST_NAME         VARCHAR(25) NOT NULL,
    LAST_NAME          VARCHAR(50) NOT NULL,
    HEIGHT             FLOAT       NOT NULL,
    WEIGHT             FLOAT       NOT NULL,
    WINGSPAN           FLOAT       NOT NULL,
    STANDING_VERTICAL  FLOAT       NOT NULL,
    MAX_VERTICAL       FLOAT       NOT NULL,
    COLLEGE            VARCHAR(25) NOT NULL,
    BIRTH_DATE         DATE        NOT NULL,
    YEARS_PRO          SMALLINT    NOT NULL,
    OVERALL            SMALLINT    NOT NULL,
    POTENTIAL          SMALLINT    NOT NULL,
    ARCHETYPE_ID       SMALLINT    NOT NULL,
    POSITION           VARCHAR(2)  NOT NULL,
    SECONDARY_POSITION VARCHAR(2)  NOT NULL,
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID),
    FOREIGN KEY (FIRST_NAME) REFERENCES FIRST_NAME (FIRST_NAME),
    FOREIGN KEY (LAST_NAME) REFERENCES LAST_NAME (LAST_NAME),
    FOREIGN KEY (COLLEGE) REFERENCES COLLEGE (COLLEGE),
    FOREIGN KEY (ARCHETYPE_ID) REFERENCES ARCHETYPE (ARCHETYPE_ID)
);

CREATE TABLE CONTRACT
(
    PLAYER_ID       INT        NOT NULL,
    LEAGUE_ID       INT        NOT NULL,
    SEASON          SMALLINT   NOT NULL,
    SALARY          FLOAT      NOT NULL,
    CONTRACT_LENGTH SMALLINT   NOT NULL,
    YEARS_REMAINING SMALLINT   NOT NULL,
    NO_TRADE_CLAUSE BOOLEAN    NOT NULL,
    CONTRACT_OPTION VARCHAR(6) NOT NULL,
    PRIMARY KEY (PLAYER_ID, LEAGUE_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    FOREIGN KEY (LEAGUE_ID, SEASON) REFERENCES LEAGUE_SEASON (LEAGUE_ID, SEASON)
);

CREATE TABLE FREE_AGENT
(
    PLAYER_ID          INT         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LEAGUE_ID          INT         NOT NULL,
    FIRST_NAME         VARCHAR(25) NOT NULL,
    LAST_NAME          VARCHAR(50) NOT NULL,
    HEIGHT             FLOAT       NOT NULL,
    WEIGHT             FLOAT       NOT NULL,
    WINGSPAN           FLOAT       NOT NULL,
    STANDING_VERTICAL  FLOAT       NOT NULL,
    MAX_VERTICAL       FLOAT       NOT NULL,
    COLLEGE            VARCHAR(25) NOT NULL,
    BIRTH_DATE         DATE        NOT NULL,
    YEARS_PRO          SMALLINT    NOT NULL,
    OVERALL            SMALLINT    NOT NULL,
    POTENTIAL          SMALLINT    NOT NULL,
    SALARY             INT         NOT NULL,
    CONTRACT_LENGTH    SMALLINT    NOT NULL,
    YEARS_REMAINING    SMALLINT    NOT NULL,
    ARCHETYPE_ID       SMALLINT    NOT NULL,
    POSITION_NAME      VARCHAR(2)  NOT NULL,
    SECONDARY_POSITION VARCHAR(2)  NOT NULL,
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (FIRST_NAME) REFERENCES FIRST_NAME (FIRST_NAME),
    FOREIGN KEY (LAST_NAME) REFERENCES LAST_NAME (LAST_NAME),
    FOREIGN KEY (COLLEGE) REFERENCES COLLEGE (COLLEGE),
    FOREIGN KEY (ARCHETYPE_ID) REFERENCES ARCHETYPE (ARCHETYPE_ID),
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE (LEAGUE_ID)
);

CREATE TABLE LEAGUE_RECORD
(
    LEAGUE_ID    INT          NOT NULL,
    PLAYER_ID    INT          NOT NULL,
    RECORD_TITLE VARCHAR(100) NOT NULL,
    RECORD_VALUE SMALLINT DEFAULT 0,
    DATE_SET     DATE         NOT NULL,
    SEASON       SMALLINT     NOT NULL,
    PRIMARY KEY (PLAYER_ID, LEAGUE_ID, SEASON, RECORD_TITLE),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    FOREIGN KEY (LEAGUE_ID, SEASON) REFERENCES LEAGUE_SEASON (LEAGUE_ID, SEASON)
);

CREATE TABLE LEAGUE_STANDINGS
(
    LEAGUE_ID INT      NOT NULL,
    TEAM_ID   INT      NOT NULL,
    SEASON    SMALLINT NOT NULL,
    WINS      SMALLINT DEFAULT 0,
    LOSSES    SMALLINT DEFAULT 0,
    PRIMARY KEY (LEAGUE_ID, SEASON, TEAM_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID),
    FOREIGN KEY (LEAGUE_ID, SEASON) REFERENCES LEAGUE_SEASON (LEAGUE_ID, SEASON)
);

CREATE TABLE PLAYER_STATS
(
    PLAYER_ID                INT      NOT NULL,
    LEAGUE_ID                INT      NOT NULL,
    SEASON                   SMALLINT NOT NULL,
    POINTS                   SMALLINT DEFAULT 0,
    REBOUNDS                 SMALLINT DEFAULT 0,
    ASSISTS                  SMALLINT DEFAULT 0,
    STEALS                   SMALLINT DEFAULT 0,
    BLOCKS                   SMALLINT DEFAULT 0,
    TURNOVERS                SMALLINT DEFAULT 0,
    GAMES_PLAYED             SMALLINT DEFAULT 0,
    FREE_THROWS_ATTEMPTED    SMALLINT DEFAULT 0,
    FREE_THROWS_MADE         SMALLINT DEFAULT 0,
    FIELD_GOALS_ATTEMPTED    SMALLINT DEFAULT 0,
    FIELD_GOALS_MADE         SMALLINT DEFAULT 0,
    THREE_POINTERS_ATTEMPTED SMALLINT DEFAULT 0,
    THREE_POINTERS_MADE      SMALLINT DEFAULT 0,
    PRIMARY KEY (PLAYER_ID, LEAGUE_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    FOREIGN KEY (LEAGUE_ID, SEASON) REFERENCES LEAGUE_SEASON (LEAGUE_ID, SEASON)
);

CREATE TABLE PLAYER_ATTRIBUTES
(
    PLAYER_ID             INT      NOT NULL,
    LEAGUE_ID             INT      NOT NULL,
    SEASON                SMALLINT NOT NULL,
    POST_HOOK             SMALLINT NOT NULL,
    POST_FADEAWAY         SMALLINT NOT NULL,
    POST_MOVES            SMALLINT NOT NULL,
    STANDING_LAYUP        SMALLINT NOT NULL,
    DRIVING_LAYUP         SMALLINT NOT NULL,
    STANDING_DUNK         SMALLINT NOT NULL,
    DRIVING_DUNK          SMALLINT NOT NULL,
    CONTACT_DUNK          SMALLINT NOT NULL,
    SHOT_CLOSE            SMALLINT NOT NULL,
    FREE_THROW            SMALLINT NOT NULL,
    MID_RANGE_OPEN        SMALLINT NOT NULL,
    MID_RANGE_OFF_DRIBBLE SMALLINT NOT NULL,
    MID_RANGE_CONTESTED   SMALLINT NOT NULL,
    THREE_PT_OPEN         SMALLINT NOT NULL,
    THREE_PT_OFF_DRIBBLE  SMALLINT NOT NULL,
    THREE_PT_CONTESTED    SMALLINT NOT NULL,
    PASSING_ACCURACY      SMALLINT NOT NULL,
    PASSING_VISION        SMALLINT NOT NULL,
    BALL_HANDLING         SMALLINT NOT NULL,
    SPEED_WITH_BALL       SMALLINT NOT NULL,
    PASSING_IQ            SMALLINT NOT NULL,
    OFFENSIVE_REBOUND     SMALLINT NOT NULL,
    DEFENSIVE_REBOUND     SMALLINT NOT NULL,
    BOX_OUT               SMALLINT NOT NULL,
    LATERAL_QUICKNESS     SMALLINT NOT NULL,
    DEFENSIVE_AWARENESS   SMALLINT NOT NULL,
    PLAY_RECOGNITION      SMALLINT NOT NULL,
    STEAL                 SMALLINT NOT NULL,
    BLOCK                 SMALLINT NOT NULL,
    PASS_PERCEPTION       SMALLINT NOT NULL,
    SHOT_CONTEST          SMALLINT NOT NULL,
    INTERIOR_DEFENSE      SMALLINT NOT NULL,
    PERIMETER_DEFENSE     SMALLINT NOT NULL,
    SPEED                 SMALLINT NOT NULL,
    STAMINA               SMALLINT NOT NULL,
    STRENGTH              SMALLINT NOT NULL,
    VERTICAL              SMALLINT NOT NULL,
    DURABILITY            SMALLINT NOT NULL,
    AGILITY               SMALLINT NOT NULL,
    ACCELERATION          SMALLINT NOT NULL,
    SHOT_IQ               SMALLINT NOT NULL,
    BASKETBALL_IQ         SMALLINT NOT NULL,
    OFFENSIVE_CONSISTENCY SMALLINT NOT NULL,
    DEFENSIVE_CONSISTENCY SMALLINT NOT NULL,
    CONFIDENCE            SMALLINT NOT NULL,
    REACTION_TIME         SMALLINT NOT NULL,
    HANDS                 SMALLINT NOT NULL,
    DRAW_FOUL             SMALLINT NOT NULL,
    PRIMARY KEY (PLAYER_ID, LEAGUE_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    FOREIGN KEY (LEAGUE_ID, SEASON) REFERENCES LEAGUE_SEASON (LEAGUE_ID, SEASON)
);

CREATE TABLE PLAYER_POTENTIAL_ATTRIBUTES
(
    PLAYER_ID             INT      NOT NULL,
    LEAGUE_ID             INT      NOT NULL,
    SEASON                SMALLINT NOT NULL,
    POST_HOOK             SMALLINT NOT NULL,
    POST_FADEAWAY         SMALLINT NOT NULL,
    POST_MOVES            SMALLINT NOT NULL,
    STANDING_LAYUP        SMALLINT NOT NULL,
    DRIVING_LAYUP         SMALLINT NOT NULL,
    STANDING_DUNK         SMALLINT NOT NULL,
    DRIVING_DUNK          SMALLINT NOT NULL,
    CONTACT_DUNK          SMALLINT NOT NULL,
    SHOT_CLOSE            SMALLINT NOT NULL,
    FREE_THROW            SMALLINT NOT NULL,
    MID_RANGE_OPEN        SMALLINT NOT NULL,
    MID_RANGE_OFF_DRIBBLE SMALLINT NOT NULL,
    MID_RANGE_CONTESTED   SMALLINT NOT NULL,
    THREE_PT_OPEN         SMALLINT NOT NULL,
    THREE_PT_OFF_DRIBBLE  SMALLINT NOT NULL,
    THREE_PT_CONTESTED    SMALLINT NOT NULL,
    PASSING_ACCURACY      SMALLINT NOT NULL,
    PASSING_VISION        SMALLINT NOT NULL,
    BALL_HANDLING         SMALLINT NOT NULL,
    SPEED_WITH_BALL       SMALLINT NOT NULL,
    PASSING_IQ            SMALLINT NOT NULL,
    OFFENSIVE_REBOUND     SMALLINT NOT NULL,
    DEFENSIVE_REBOUND     SMALLINT NOT NULL,
    BOX_OUT               SMALLINT NOT NULL,
    LATERAL_QUICKNESS     SMALLINT NOT NULL,
    DEFENSIVE_AWARENESS   SMALLINT NOT NULL,
    PLAY_RECOGNITION      SMALLINT NOT NULL,
    STEAL                 SMALLINT NOT NULL,
    BLOCK                 SMALLINT NOT NULL,
    PASS_PERCEPTION       SMALLINT NOT NULL,
    SHOT_CONTEST          SMALLINT NOT NULL,
    INTERIOR_DEFENSE      SMALLINT NOT NULL,
    PERIMETER_DEFENSE     SMALLINT NOT NULL,
    SPEED                 SMALLINT NOT NULL,
    STAMINA               SMALLINT NOT NULL,
    STRENGTH              SMALLINT NOT NULL,
    VERTICAL              SMALLINT NOT NULL,
    DURABILITY            SMALLINT NOT NULL,
    AGILITY               SMALLINT NOT NULL,
    ACCELERATION          SMALLINT NOT NULL,
    SHOT_IQ               SMALLINT NOT NULL,
    BASKETBALL_IQ         SMALLINT NOT NULL,
    OFFENSIVE_CONSISTENCY SMALLINT NOT NULL,
    DEFENSIVE_CONSISTENCY SMALLINT NOT NULL,
    CONFIDENCE            SMALLINT NOT NULL,
    REACTION_TIME         SMALLINT NOT NULL,
    HANDS                 SMALLINT NOT NULL,
    DRAW_FOUL             SMALLINT NOT NULL,
    PRIMARY KEY (PLAYER_ID, LEAGUE_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    FOREIGN KEY (LEAGUE_ID, SEASON) REFERENCES LEAGUE_SEASON (LEAGUE_ID, SEASON)
);

CREATE TABLE ATTRIBUTE
(
    NAME        VARCHAR(30)  NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CATEGORY    VARCHAR(30)  NOT NULL,
    PRIMARY KEY (NAME)
);

CREATE TABLE APP_TIP
(
    TITLE   VARCHAR(30)  NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    PRIMARY KEY (TITLE)
);

CREATE TABLE VIEW_DESCRIPTION
(
    TITLE   VARCHAR(9)   NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    PRIMARY KEY (TITLE)
);
