spring.datasource.url=jdbc:db2://dashdb-txn-sbox-yp-lon02-04.services.eu-gb.bluemix.net:50001/BLUDB:sslConnection=true;
spring.datasource.username=xhq93883
spring.datasource.password=2vw13s204kc5@b2v
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.dbcp2.test-while-idle=true
spring.datasource.dbcp2.validation-query=SELECT 1
spring.datasource.hikari.connection-test-query=VALUES 1
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DB2Dialect
management.endpoints.web.exposure.include=httptrace
management.trace.http.include=RESPONSE_HEADERS
management.endpoints.enabled-by-default=true
# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
debug=false
server.servlet.application-display-name=Basketball Simulator
spring.thymeleaf.cache=false
spring.main.banner-mode=off
logging.level.org.springframework.web=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=ERROR
logging.level.jdbc.resultsettable=ERROR
# Custom Properties
backend.app.title=Basketball Simulator
backend.app.port=8100
